name: EVENTS
favicon: null
layout_spectrum: 0.62377
typography_spectrum: 0.79393
title: 'EVENTS & GALLERY'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7941d'
    - '#000000'
    - '#ffffff'
    - '#b7b8bd'
    - '#636466'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
