name: CSGALLERY
favicon: null
layout_spectrum: 0.7853509401902556
typography_spectrum: 0.926693968474865
title: 'EVENTS & GALLERY'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2838302559684962
  lightness: 0.687051567947492
  saturation: 0.4496110107284039
  rhythmicContrast: 0.48098431969992816
purpose: []
